### PR TITLE
chore: Add emoji to main prompt choices

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
### Changes
Add emoji to main prompt choices

Screenshot 2023-03-18 at 6 15 56 PM

### CODE REVIEW

**Review by Ananya2001-an — APPROVED** [review]
Looks good! 👍 Nothing can go wrong with emojis... ✌️

**Comment by Pradumnasaraf** [comment]
I need to work on my spelling I think 🤦

**Comment by Ananya2001-an** [comment]
> I need to work on my spelling I think 🤦

haha

**Comment by Ananya2001-an** [comment]
I am going to merge this then

**Comment by Pradumnasaraf** [comment]
You can merge it when you see an https://github.com/Pradumnasaraf/LinkFree-CLI/labels/Ready-for-review label. You don't need to ask. This is why I created that label.

**Comment by Ananya2001-an** [comment]
> You can merge it when you see an [ Ready-for-review](https://github.com/Pradumnasaraf/LinkFree-CLI/labels/Ready-for-review) label. You don't need to ask. This is why I created that label.

Yeah I understood that just wanted to confirm once.

**Comment by Pradumnasaraf** [comment]
Thank you.

**Comment by Ananya2001-an** [comment]
You are welcome as always 👍

**Pull request merged**
