### PR TITLE
feat: created remove and update functions for all keys

### PR DESCRIPTION
**Pull request by Ananya2001-an**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Ananya2001-an** [comment]
Hey @Pradumnasaraf review the PR when you get time. I have created the update and delete functions for all keys. There are still some small things that we need to fix but I have kept them for later.

**Comment by Pradumnasaraf** [comment]
Hey, Ananya. 

Thanks for the PR. I will review it soon. Also, looks like you synced changes in your branch with `main`, this is why some commits are reflecting. 

Screenshot 2023-02-19 at 2 16 23 PM

Can you please revert them?

**Comment by Ananya2001-an** [comment]
> Hey, Ananya. 
> 
> Thanks for the PR. I will review it soon. Also, looks like you synced changes in your branch with `main`, this is why some commits are reflecting. 
> 
> Screenshot 2023-02-19 at 2 16 23 PM
> 
> Can you please revert them?

Yeah sure

**Comment by Pradumnasaraf** [comment]
Thank you. This is why it says `1277` lines of addition. For a min, I got freaked away. 😅 

Screenshot 2023-02-19 at 2 21 59 PM

**Comment by Ananya2001-an** [comment]
> Thank you. This is why it says `1277` lines of addition. For a min, I got freaked away. 😅 
> 
> Screenshot 2023-02-19 at 2 21 59 PM
> 

Actually I synced my main branch with your main branch that's why these changes got added in the feature branch as well.

**Comment by Pradumnasaraf** [comment]
> Actually I synced my main branch with your main branch that's why these changes got added in the feature branch as well.

Yes, I guess I guess that above right https://github.com/Pradumnasaraf/LinkFree-CLI/pull/27#issuecomment-1435928321

**Comment by Ananya2001-an** [comment]
Hey @Pradumnasaraf made the reverts. I hope it's fine now.

**Comment by Pradumnasaraf** [comment]
Thanks, I will soon review it.

**Review by Pradumnasaraf — APPROVED** [review]
Hey, 

It's really great to see how the update JSON function is working so well. If I was working on it, I have not made it work TBH. I am still digesting the code for update functions, haha. 

Again, thank you for your time and great work.

**Looks good to merge.**

**Comment by Pradumnasaraf** [comment]
Shall I merge this?

**Comment by Ananya2001-an** [comment]
> Shall I merge this?

Yeah I guess it looks good from my end.

**Comment by Pradumnasaraf** [comment]
Awesome.

**Pull request merged**
