### PR TITLE
fix: color combination for chalk prompt

### LINKED ISSUE #38: [BUG]  Fix the light BG
### What would you like to share?

hii, maintainers please remove the light bg or add dark bg. 

image

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
## 🛠️ Fixes Issue

fixes #38 

## 👨‍💻 Changes proposed

- Set the attribute for text color as well previously it was only for the background
- Fix the wrong license in `package.json` and `package-lock.json`
- Fix the Greeting message because we have a maintainer now - `.github/workflows/greetings.yml`.

## Fix:

```js
chalk.bgWhite.bold

to

chalk.black.bgWhite.bold // the black will set the color for the text and bgWhite for the background,
```

### CODE REVIEW

**Review by Ananya2001-an — APPROVED** [review]
Looks good 👍

**Comment by Ananya2001-an** [comment]
Shall I merge it?

**Comment by Pradumnasaraf** [comment]
Yes 100%

Also, sorry fo pinning it for the review. I don't do that, because people have other works and property, but this was a huge accessibility issue and we shared it on social for people to use.

**Comment by Ananya2001-an** [comment]
> Yes 100%
> 
> Also, sorry fo pinning you for the review. I don't do that, because people have other work and priorities, but this was a huge accessibility issue and we shared it on social for people to use.
> 

No worries. You can bug me anytime u want. I have my phone after all 👍😂

**Comment by Pradumnasaraf** [comment]
> > Yes 100%
> > Also, sorry fo pinning you for the review. I don't do that, because people have other work and priorities, but this was a huge accessibility issue and we shared it on social for people to use.
> 
> No worries. You can bug me anytime u want. I have my phone after all 👍😂

Do you test everything on phone 🤔 ?

**Comment by Ananya2001-an** [comment]
> > > Yes 100%
> > > Also, sorry fo pinning you for the review. I don't do that, because people have other work and priorities, but this was a huge accessibility issue and we shared it on social for people to use.
> > 
> > No worries. You can bug me anytime u want. I have my phone after all 👍😂
> 
> Do you test everything on phone 🤔 ?
> 
> Thanks for the merge

No ofc I use my laptop for reviewing the major changes but if it's something small then in that case I just check the code.

**Comment by Pradumnasaraf** [comment]
> No ofc I use my laptop for reviewing the major changes but if it's something small then in that case I just check the code. 

Gotha. 

I have created and merged PR in LinkFree as well to change the version.

**Pull request merged**
