### PR TITLE
add: Added profile data for Shivam Jha

### PR DESCRIPTION
**Pull request by jhashivam-2001**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers
Hey there, just added my profile data. Please merge !

### CODE REVIEW

**Comment by Ananya2001-an** [comment]
Hey @jhashivam-2001 you need to use LinkFree CLI inside your clone of LinkFree repo to create a JSON profile and then raise a PR to LinkFree so that they can merge it. We need to close this PR. If you still have any doubts feel free to ask.

**Comment by Pradumnasaraf** [comment]
Hey, @jhashivam-2001, great to see you here.

+1 what Ananaya said. 

A wild guess, you followed the developing guidelines instead of the [Using the CLI tool](https://github.com/Pradumnasaraf/LinkFree-CLI#-using-the-cli-tool) step. Please follow this https://linkfree.eddiehub.io/docs/environments/linkfree-cli

Screenshot 2023-02-27 at 11 30 50 AM

**Comment by jhashivam-2001** [comment]
That is what I did 😂

**Comment by Pradumnasaraf** [comment]
> That is what I did 😂

Ah, I guessed it right. No worries you can follow the step. I will merge PR in LinkFree ASAP.

**Pull request closed without merging**
