### PR TITLE
chore: minor refactoring and docs update

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
- Remove test data - **Done**
  - Bump up the version manually in `package.json` and `package-lock.json` **Done**
  - Update CHANGELOG.md **Done**
  - Update README with the new GIF, steps, and features. **Done**

Some cleanup :)

### CODE REVIEW

**Review by Ananya2001-an — COMMENTED** [review]
Looks good 👍

**Comment by Pradumnasaraf** [comment]
> Looks good 👍

Thank you. Just looking for small things which can be fixed before released. You can have a look as well.

We will create realise at ~10:30 AM IST

**Comment by Pradumnasaraf** [comment]
Also, did you have a look at the Release note? https://github.com/Pradumnasaraf/LinkFree-CLI/releases/tag/untagged-66b76f96b2a358fc6091 . This is a super important thing who contributed

**Comment by Ananya2001-an** [comment]
> Also, did you have a look at the Release note? https://github.com/Pradumnasaraf/LinkFree-CLI/releases/tag/untagged-66b76f96b2a358fc6091 . This is a super important thing who contributed
> 
> (Hope you can see that as it's in draft)

Looks awesome Pradumna. Thanks for the shoutout 😁❤

**Comment by Pradumnasaraf** [comment]
> > Also, did you have a look at the Release note? https://github.com/Pradumnasaraf/LinkFree-CLI/releases/tag/untagged-66b76f96b2a358fc6091 . This is a super important thing who contributed
> > (Hope you can see that as it's in draft)
> 
> Looks awesome Pradumna. Thanks for the shoutout 😁❤

No, thank you. For all your hard word and knowlege

**Comment by Ananya2001-an** [comment]
> > Looks good 👍
> 
> Thank you. Just looking for small things which can be fixed before released. You can have a look as well.
> 
> We will create realise at ~10:30 AM IST

Ooohh exciting let's have a countdown timer 😂

**Comment by Pradumnasaraf** [comment]
> > > Looks good 👍
> > 
> > 
> > Thank you. Just looking for small things which can be fixed before released. You can have a look as well.
> > We will create realise at ~10:30 AM IST
> 
> Ooohh exciting let's have a countdown timer 😂

Making fun of me 👀 

I by mistake wrote 10:30 it's 12

**Comment by Pradumnasaraf** [comment]
I am so many typos 😅

**Comment by Ananya2001-an** [comment]
> I make so many typos 😅 

It's actually good sometimes. I have a bad habit of fixing all typos while writing which makes me really slow at getting things done quickly.  Typos are something that can be fixed later.

**Comment by Pradumnasaraf** [comment]
> > I make so many typos 😅
> 
> It's actually good sometimes. I have a bad habit of fixing all typos while writing which makes me really slow at getting things done quickly. Typos are something that can be fixed later.

Thank you, I will take this advice, haha

**Comment by Pradumnasaraf** [comment]
Right now I am finding some way to make a CLI mock-up I see on some good websites. Do you know any?

**Comment by Ananya2001-an** [comment]
> Right now I am finding some way to make a CLI mock-up I see on some good websites. Do you know any?

I know this site called dribbble idk if it will help but you should check it out

**Comment by Pradumnasaraf** [comment]
> > Right now I am finding some way to make a CLI mock-up I see on some good websites. Do you know any?
> 
> I know this site called dribbble idk if it will help but you should check it out

I checked, but I didn't find any 😅 . Need something like https://www.snipli.xyz/

**Comment by Ananya2001-an** [comment]
> > > Right now I am finding some way to make a CLI mock-up I see on some good websites. Do you know any?
> > 
> > I know this site called dribbble idk if it will help but you should check it out
> 
> I checked, but I didn't find any 😅 . Need something like https://www.snipli.xyz/

Okay I will search from my end and send you the link once I find something

**Comment by Pradumnasaraf** [comment]
Thank you

**Comment by Pradumnasaraf** [comment]
Hey @Ananya2001-an 

If you looking for it, you can stop. I am making my own from scratch.

**Comment by Ananya2001-an** [comment]
> Hey @Ananya2001-an
> 
> If you looking for it, you can stop. I am making my own from scratch.

Okay great because I am not getting any such place where we can make this. Idk how others do this? Still ask me for any help if you need

**Comment by Pradumnasaraf** [comment]
> > Hey @Ananya2001-an
> > If you looking for it, you can stop. I am making my own from scratch.
> 
> Okay great because I am not getting any such place where we can make this. Idk how others do this? Still ask me for any help if you need

The use some paid tools. Sure I will ask

**Comment by Pradumnasaraf** [comment]
Hey @Ananya2001-an 

How does it look? I have to create so many fake and dummy images and video and overlap reach other

**Comment by Ananya2001-an** [comment]
> Hey @Ananya2001-an
> 
> How does it look? I have to create so many fake and dummy images and videos and overlap each other https://www.canva.com/design/DAFbXRIc1Xo/MCrodh0211vaLC6z3z6Weg/watch?utm_content=DAFbXRIc1Xo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Looks amazing!!!

**Comment by Pradumnasaraf** [comment]
> > Hey @Ananya2001-an
> > How does it look? I have to create so many fake and dummy images and videos and overlap each other https://www.canva.com/design/DAFbXRIc1Xo/MCrodh0211vaLC6z3z6Weg/watch?utm_content=DAFbXRIc1Xo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
> 
> Looks amazing!!!

Awesome. Let's go with that.

Thanks for the quick feeback

**Comment by Pradumnasaraf** [comment]
Go ahead merge it :)

**Comment by Pradumnasaraf** [comment]
Thank you!

**Comment by Ananya2001-an** [comment]
Drum roll for the big moment now 🥁

**Comment by Pradumnasaraf** [comment]
YEEESSS!

drums

**Pull request merged**
