### PR TITLE
fix: removes keys from json

### PR DESCRIPTION
**Pull request by Ananya2001-an**
We are able to remove keys from json file when their values are empty after delete operations. Also made other random fixes.

### CODE REVIEW

**Comment by Ananya2001-an** [comment]
Hey @Pradumnasaraf made the fixes. Review when you get free.

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you. It work like a chram

**Comment by Ananya2001-an** [comment]
> Looks good to merge. Thank you. It work like a chram

Great I guess we can release the new version now 🌈

**Comment by Pradumnasaraf** [comment]
I am still digesting how update and remove is working 😅 

BTW I git a little bit about what this is doing can you explain a little bit.

```js
  choiceSocials.map((social) => {
    social.name = social.url;
  });
```

**Comment by Pradumnasaraf** [comment]
> > I am still digesting how update and remove is working 😅
> > BTW I git a little bit about what this is doing can you explain a little bit.
> > ```js
> >   choiceSocials.map((social) => {
> >     social.name = social.url;
> >   });
> > ```
> 
> Yeah actually in select the choices show the names and here we have no name so I had to do this explicitly to show something to the user to select from

Ah got it. Thank you.

**Comment by Pradumnasaraf** [comment]
> > Looks good to merge. Thank you. It work like a chram
> 
> Great I guess we can release the new version now 🌈

Yes, one more PR is on the way in 1-2 min. That crazy idea just came into my mind.

**Comment by Ananya2001-an** [comment]
> > > Looks good to merge. Thank you. It work like a chram
> > 
> > Great I guess we can release the new version now 🌈
> 
> Yes, one more PR is on the way in 1-2 min. That crazy idea just came into my mind.

Awesome

**Pull request merged**
