### PR TITLE
feat: add events

### PR DESCRIPTION
**Pull request by Ananya2001-an**
## 👨‍💻 Changes proposed

Created addEvents function

## 📄 Note to reviewers

Hey @Pradumnasaraf. I created the addEvents function. But there is one small issue that the date format is not the same as we want. After converting it into a date object we are getting something like this: `2023-08-09T00:00:00.000Z` but it should be like this `2023-08-09T00:00:00.000+00:00` instead.

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey, Thanks for the PR. 

About think about the issue. We should then go with talking the complete input from the user because this format might be with the LinkFree, so there is a risk. Also, it will become simpler for us as well to handle no internal conversion

Later we can try to come up with some solution using some tool or API. We can just put the sample format in the bracket when we prompt the message for data.

What is your take on this?

**Comment by Ananya2001-an** [comment]
> Hey, Thanks for the PR. 
> 
> About the issue. We should then go with talking the complete input from the user because this format might be with the LinkFree, so there is a risk. Also, it will become simpler for us as well to handle no internal conversion
> 
> Later we can try to come up with some solution using some tool or API. We can just put the sample format in the bracket when we prompt the message for data.
> 
> What is your take on this?
> 

But isn't this difficult for a user to give because the date is fine but after that the timestamp part is something that the user should understand before writing anything

**Comment by Pradumnasaraf** [comment]
> > Hey, Thanks for the PR.
> > About the issue. We should then go with talking the complete input from the user because this format might be with the LinkFree, so there is a risk. Also, it will become simpler for us as well to handle no internal conversion
> > Later we can try to come up with some solution using some tool or API. We can just put the sample format in the bracket when we prompt the message for data.
> > What is your take on this?
> 
> But isn't this difficult for a user to give because the date is fine but after that the timestamp part is something that the user should understand before writing anything

I agree with you 100%. This is why when we discussed about this, I said we need to make it easier at the user end (convert internally). But we have no option. We can't make JSON that the wrong format which will not work with LinkFree.

**Comment by Pradumnasaraf** [comment]
>But isn't this difficult for a user to give because the date is fine but after that the timestamp part is something that the user should understand before writing anything 

I agree with you 100%. This is why when we discussed about this, I said we need to make it easier at the user end (convert internally). But we have no option. We can't make JSON that the wrong format which will not work with LinkFree.

**Comment by Ananya2001-an** [comment]
> >But isn't this difficult for a user to give because the date is fine but after that the timestamp part is something that the user should understand before writing anything 
> 
> I agree with you 100%. This is why when we discussed about this, I said we need to make it easier at the user end (convert internally). But we have no option. We can't make JSON in the wrong format which will not work with LinkFree.

Let me do one thing only the Z part at the end has to be replaced with something like +00:00 so I think I will keep this as default for now and later we can come up with a solution

**Comment by Pradumnasaraf** [comment]
> > > But isn't this difficult for a user to give because the date is fine but after that the timestamp part is something that the user should understand before writing anything
> > 
> > 
> > I agree with you 100%. This is why when we discussed about this, I said we need to make it easier at the user end (convert internally). But we have no option. We can't make JSON in the wrong format which will not work with LinkFree.
> 
> Let me do one thing only the Z part at the end has to be replaced with something like +00:00 so I think I will keep this as default for now and later we can come up with a solution

Din't get you

**Comment by Ananya2001-an** [comment]
`2023-08-09T00:00:00.000Z `
this is the current output and what we want is that the Z at the end should be something like +00:00

**Comment by Pradumnasaraf** [comment]
Sure, you can have a look. But I suggest going with complete user input because date and time things are tricky.

**Comment by Pradumnasaraf** [comment]
Also, we are taking only the date as the input, not the time. That means time will always be 0

**Comment by Pradumnasaraf** [comment]
> Fine I think I will make the changes like I suggested before as time doesn't really matter that much

No, it matters because we are adding a conference to the map which requires time to show nearby conference

**Comment by Ananya2001-an** [comment]
Okayyy that's a problem. Fine I will keep it as user input then.

**Comment by Ananya2001-an** [comment]
Hey @Pradumnasaraf you can review the PR now. I have kept the date input completely upto user. No internal conversions done.

**Review by Pradumnasaraf — COMMENTED** [review]
Hey, thanks for the changes. Small suggestions

In the prompt, we should add a little clear message that we are expecting both a date and time and also a sample for ease. Something like this

```diff
- message: "Give event start date",
+ message: "Give event start date and time. (Supported format: 2023-08-09T00:00:00.000+00:00),
```

**Comment by Ananya2001-an** [comment]
Done the changes @Pradumnasaraf

**Review by Pradumnasaraf — APPROVED** [review]
Looks good to merge. Thank you for the changes.

Also, thanks for fixing that `writter` typo in other files

**Comment by Ananya2001-an** [comment]
> Looks good to merge. Thank you for the changes.
> 
> Also, thanks for fr fix that `writter` typo in other files

No worries.

**Comment by Pradumnasaraf** [comment]
Should we merge it?

**Comment by Ananya2001-an** [comment]
> Should we merge it?

yeah go ahead

**Comment by Pradumnasaraf** [comment]
Done

Amazing. All 4 major parts are done.

**Comment by Ananya2001-an** [comment]
> Done
> 
> Amazing. All 4 major parts are done.

Yeah finally. I think we have to just look into some small fixes here and there and then we are good to go!

**Comment by Pradumnasaraf** [comment]
> > Done
> > Amazing. All 4 major parts are done.
> 
> Yeah finally. I think we have to just look into some small fixes here and there and then we are good to go!

Yep, 100%. BTW a small shootout to you again. If you haven't opened the issues on the repo. I was not planning to do the CLI right now and not 2.0.0.

**Comment by Pradumnasaraf** [comment]
Thank you. I learned a lot from out. About structuring and code.

**Comment by Ananya2001-an** [comment]
> Thank you. I learned a lot from out. About structuring and code.

Me too. I never worked on a cli tool before so it was nice to have a project that was easy to work with.

**Comment by Pradumnasaraf** [comment]
> > Thank you. I learned a lot from out. About structuring and code.
> 
> Me too. I never worked on a cli tool before so it was nice to have a project that was easy to work with.

Oh wow, I didn't know this was your 1st time on a CLI. Your contributors were huge 👏

**Comment by Ananya2001-an** [comment]
> > > Thank you. I learned a lot from out. About structuring and code.
> > 
> > 
> > Me too. I never worked on a cli tool before so it was nice to have a project that was easy to work with.
> 
> Oh wow, I didn't know this was your 1st time on a CLI. Your contributors were huge 👏

haha fake it till u make it. I have learned that with time.

**Comment by Pradumnasaraf** [comment]
Also, forgot to ask you before, would you like to be Maintainer?

**Comment by Ananya2001-an** [comment]
> Also, forgot to ask you before, would you like to be a Maintainer?

Ohhh yessss I would love to. Thanks for asking @Pradumnasaraf This is an amazing project and I would love to be a part of it. 😁

**Comment by Pradumnasaraf** [comment]
No, thank you for accepting. Set you an invite :).

**Comment by Ananya2001-an** [comment]
> No, thank you for accepting. Sent you an invite :).

Accepted! 😀

**Comment by Ananya2001-an** [comment]
> Awesome. Welcome 🎉 . This is the 1st time, I onboarded a maintainer on one of my projects.

Congrats to u too then 👏

**Comment by Pradumnasaraf** [comment]
> > Awesome. Welcome 🎉 . This is the 1st time, I onboarded a maintainer on one of my projects.
> 
> Congrats to u too then 👏 

Thank you.

**Pull request merged**
