### PR TITLE
docs: update README

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
## 👨‍💻 Changes proposed

- Replace the CLI using steps with the LinkFree docs - https://linkfree.eddiehub.io/docs/environments/linkfree-cli

## ✔️ Check List (Check all the applicable boxes) 

- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey, @Ananya2001-an. You can review that.

Also, when we create PRs, we can start using https://github.com/Pradumnasaraf/LinkFree-CLI/labels/Ready-for-review label to avoid confusion in understanding if the PR is ready for review or not.

**Review by Ananya2001-an — APPROVED** [review]
Looks great 👍

**Comment by Ananya2001-an** [comment]
Shall I merge it?

**Comment by Pradumnasaraf** [comment]
> Shall I merge it?

Yes, go ahaed

**Pull request merged**
