### PR TITLE
BREAKING CHANGES: v2.0.0

### LINKED ISSUE #16: [FEATURE] Allowing only some changes when overwriting
### Description

Currently when the users are allowed to overwrite their profile we are asking them to write everything from scratch. How about also asking them if they want to keep that field as it is? If not then they can overwrite or add anything they want to.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
### Breaking Changes

- The CLI now uses a different function/folder handling structure. This means the newer version features will not work with the older version of the CLI. Please update to the latest version of the CLI to use the new features.

### Features

- Added support to update the JSON function  https://github.com/Pradumnasaraf/LinkFree-CLI/pull/24 - **Ananya**
- Add support to add milestones, socials, and tags https://github.com/Pradumnasaraf/LinkFree-CLI/pull/26 - **Pradumna**
- Add support to create remove and update keys by  https://github.com/Pradumnasaraf/LinkFree-CLI/pull/27 - **Ananya**
- Add support for testimonials https://github.com/Pradumnasaraf/LinkFree-CLI/pull/29 - **Ananya**
- Add support to add events https://github.com/Pradumnasaraf/LinkFree-CLI/pull/30 - **Pradumna**
- Add supported to for optional key to Events and Milestone https://github.com/Pradumnasaraf/LinkFree-CLI/pull/32 https://github.com/Pradumnasaraf/LinkFree-CLI/pull/33 - **Pradumna**
- Support for reporting a bug from CLI https://github.com/Pradumnasaraf/LinkFree-CLI/pull/35 - **Pradumna**

### Fix
* Removes empty keys from json when value is not there https://github.com/Pradumnasaraf/LinkFree-CLI/pull/34 - **Ananya**

## Fix - Issue closes

closes #16

Mian prompt
Screenshot 2023-02-23 at 11 58 24 AM

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Let get that final review comes in @Ananya2001-an 🎉

**Review by Ananya2001-an — APPROVED** [review]
I feel proud of @Ananya2001-an and @Pradumnasaraf to have done such an amazing work with so much patience and dedication. Kudos to both of you😁😂💙

**Comment by Pradumnasaraf** [comment]
> I feel proud of @Ananya2001-an and @Pradumnasaraf to have done such an amazing work with so much patience and dedication. Kudos to both of you😁😂💙

LOL. Thank you and shoutout to you 💙

**Comment by Ananya2001-an** [comment]
Let's merge this Pradumna. Do the honors please.

**Comment by Pradumnasaraf** [comment]
> Let's merge this Pradumna. Do the honors please.

Sure. Thank you. Just checking the actions for final time

**Comment by Pradumnasaraf** [comment]
I was going to the stupidy by squash and merge 🤣 . It needs to be a simple merge so that all our commits should reflect separately

**Comment by Ananya2001-an** [comment]
> I was going to the stupidy by squash and merge 🤣 . It needs to be a simple merge so that all our commits should reflect separately

Thank god

**Comment by Pradumnasaraf** [comment]
MERGED. LET's GOOOOO!

**Comment by Ananya2001-an** [comment]
> MERGED. LET's GOOOOO!

Congrats! Finally people can use it. Makes me happy 🤗

**Comment by Pradumnasaraf** [comment]
> > MERGED. LET's GOOOOO!
> 
> Congrats! Finally people can use it. Makes me happy 🤗

YAY ❤️ . on NPM as well https://www.npmjs.com/package/linkfree-cli

**Comment by Ananya2001-an** [comment]
> > > MERGED. LET's GOOOOO!
> > 
> > 
> > Congrats! Finally people can use it. Makes me happy 🤗
> 
> YAY ❤️ . It's live on NPM as well https://www.npmjs.com/package/linkfree-cli

Awesome!

**Comment by Ananya2001-an** [comment]
Shall I delete this branch refactor-cli now?

**Comment by Pradumnasaraf** [comment]
> Shall I delete this branch refactor-cli now?

Yes sure!

**Pull request merged**
