### PR TITLE
feat: report bug from CLI - main prompt

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
- We can report bugs from the CLI and it will pre-populate the data in GitHub issues

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey, @Ananya2001-an 

Have a play with it. Let me what you think. I always wanted to use GitHub issues pre-data population in something. Let me know if we can include this. This a crazy idea

**Comment by Ananya2001-an** [comment]
Can you send me a screen record actually I can't use my laptop right now

**Comment by Pradumnasaraf** [comment]
> Can you send me a screen recording actually I can't use my laptop right now

Yep sure

https://user-images.githubusercontent.com/51878265/220725748-18bcb78e-3626-47c9-ac1f-8a4f5a9639eb.mov

You can review it tomorrow. We can merge this PR tomorrow.

**Comment by Ananya2001-an** [comment]
I saw the code and it looks good but this will only work if none of the 4 choices are selected so when will that happen?

**Comment by Ananya2001-an** [comment]
Ignore my last comment I didn't see that you have added the 5th option of report a bug😂

**Comment by Ananya2001-an** [comment]
> > Can you send me a screen recording actually I can't use my laptop right now
> 
> Yep sure
> 
> https://user-images.githubusercontent.com/51878265/220725748-18bcb78e-3626-47c9-ac1f-8a4f5a9639eb.mov
> 
> You can review it tomorrow. We can merge this PR tomorrow.

This looks amazing let's have it

**Comment by Pradumnasaraf** [comment]
> Ignore my last comment I didn't see that you have added the 5th option of report a bug😂

Ah, no worries. LIke this Idea?

**Comment by Ananya2001-an** [comment]
Things like this make me love cli more💖

**Comment by Pradumnasaraf** [comment]
YOu can approve and merge this PR. Rember to choose **squash and merge**

**Comment by Ananya2001-an** [comment]
> > Things like this make me love cli more💖
>  
>  I still can't believe we made it

Team efforts always go well😎

**Comment by Ananya2001-an** [comment]
> You can approve and merge this PR. Rember to choose **squash and merge**
> 
> Challenge for you to do this on a phone 👀 

Challenge accepted

**Review by Ananya2001-an — APPROVED** [review]

**Comment by Pradumnasaraf** [comment]
Thank you. For the merge

**Comment by Ananya2001-an** [comment]
> Thank you. For the merge 

You're always welcome

**Comment by Pradumnasaraf** [comment]
Hopefully, we will release `v2.0.0` by tomorrow

But before that, I need to do tons of work and preapre😅 
- Changelog
- Release Notes
- Docs 
- Maybe something more

**Comment by Ananya2001-an** [comment]
> Hopefully, we will release `v2.0.0` by tomorrow
> 
> But before that, I need to do tons of work and preapre😅 
> - Changelog
> - Release Notes
> - Docs 
> - Maybe something more

Good luck on that 👍😂 definitely ask me for help on anything you need

**Comment by Pradumnasaraf** [comment]
> Good luck on that 👍😂 definitely ask me for help on anything you need

Sure, thank you

**Pull request merged**
