### PR TITLE
feat: Convert code to ES6 modules

### LINKED ISSUE #70: [FEATURE] Change to ES6
### Description

Some of the dependencies we using are old versions and some are highly vulnerable. To use the lastest version we need to start using the ES6 standards.

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
## 🛠️ Fixes Issue

Closes #70 

## 👨‍💻 Changes proposed

- Upgrade all dependencies to the latest
- Change in the import and export statement statements

### CODE REVIEW

**Comment by Ananya2001-an** [comment]
Hey @Pradumnasaraf yeah it's cool I will check it out when I get free and yes it's a good decision to change it to ES6 👍

**Comment by Ananya2001-an** [comment]
Awesome that u added the search profile as well 😀 did u just use the public api?

**Review by Ananya2001-an — APPROVED** [review]
It looks good! Also just a suggestion but maybe we should add some unit tests later on to check whether the function logic is working well or not...just makes it easier to maintain, we can use jest for that maybe :) But you can add it to the backlog for now.

**Comment by Pradumnasaraf** [comment]
Thank you so much, @Ananya2001-an, for checking. 

Yes, I want to add testing soon. But I have limited knowledge, and I always get confused because there are so many kinds of tests lol and I struggle to find good resources to learn about them. Yes, I will put that in the backlog, and someday with your help, we will add that.

**Comment by Pradumnasaraf** [comment]
Thank you so much, @Ananya2001-an, for checking. 

Yes, I want to add testing soon. But I have limited knowledge, and I always get confused because there are so many kinds of tests lol and I struggle to find good resources to learn about them. Yes, I will put that in the backlog, and someday with your help, we will add that.

**Comment by Ananya2001-an** [comment]
Awesome!

**Pull request merged**
